GET http://localhost:3000/players/




GET http://localhost:3000/players/5/





GET http://localhost:3000/matches/5/

GET http://localhost:3000/players/5/matches

GET http://localhost:3000/matches/3/players


GET http://localhost:3000/players/8/playerScores